version: "3"
services:
  database:
    container_name: database
    image: postgis/postgis:13-master
    volumes:
      - ./backend/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"
  cache:
    image: redis:6
  directus:
    container_name: directus
    image: directus/directus:10.10.2
    ports:
      - "8055:8055"
    volumes:
      - my_uploads:/directus/uploads
      - my_extensions:/directus/extensions
      - "./backend/snapshots:/directus/snapshots"

    depends_on:
      - cache
      - database
    environment:
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"
      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"
      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"
      CORS_METHODS: "GET,POST,PUT,DELETE"
      CORS_ALLOWED_HEADERS: "Content-Type,Authorization,X-Requested-With"
      CORS_EXPOSED_HEADERS: "Content-Range,X-Content-Range"
  frontend:
    container_name: frontend
    ports:
      - "3000:3000"
volumes:
  my_uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./backend/uploads
  my_extensions:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./backend/extensions
