import Sidebar from "@/src/components/_Dashboard/sidebar/sidebar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <Sidebar children={children} />;
}
