name: Deploy on Production

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd www/msp
            git pull origin prod
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml down
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up --build -d
            LATEST_SNAPSHOT=$(ls -Art ./backend/snapshots/*.yaml | tail -n 1)
            echo "Applying latest snapshot: $LATEST_SNAPSHOT"
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec -T directus npx directus schema apply $LATEST_SNAPSHOT
